# Generated by Django 3.2 on 2022-12-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_groupquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupquestion',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.groupquestion'),
        ),
    ]
