# Generated by Django 3.2 on 2022-12-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20221202_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupquestion',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
