# Generated by Django 3.2 on 2022-12-13 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20221213_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='question',
        ),
        migrations.AddField(
            model_name='result',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questions.groupquestion'),
        ),
    ]
