# Generated by Django 3.2 on 2022-12-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20221213_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='group_name',
            field=models.CharField(max_length=25),
        ),
    ]
