# Generated by Django 3.2 on 2022-12-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_alter_groupquestion_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupquestion',
            name='group_name',
            field=models.CharField(max_length=20),
        ),
    ]
